### ISSUE TITLE
getting started with ipfs

### ISSUE THREAD

**Issue by AbuSantos** [UrbanWill/nft-marketplace#3]
could you please help on the ipfs settings

**Comment by UrbanWill** [comment]
Yes, can you let me know what is the behavior you are experiencing and what the expected behavior would be? Perhaps error logs?

**Comment by UrbanWill** [comment]
@AbuSantos IPFS recently went through some changes and pulled a sneaky on me.

- Solution: https://community.infura.io/t/error-create-token-httperror-project-id-required/5679/4
- Implementation: https://github.com/UrbanWill/nft-marketplace/pull/7
