### ISSUE TITLE
Infura Access to public Gateway deprecated

### ISSUE THREAD

**Issue by wernerlinsler** [UrbanWill/nft-marketplace#4]
Since 10th August 2022 there is no access to the public gateway of Infura!. The Infura gateway endpoints must adapted. 
Look at  "https://blog.infura.io/post/ipfs-public-api-and-gateway-deprecation":
....... Please ensure that, by Wednesday 10th August 2022 you will have migrated your endpoints over to the authenticated API endpoints within your project settings, enabled the dedicated gateway, and changed your gateway endpoints at any place where you access the gateway within your IPFS dApps/code. ......

**Comment by UrbanWill** [comment]
Thanks for pointing this out!

I will be working on updating this soon 😄
